name: webapp
namespace: chatbot-ns

replicas: 3
restartPolicy: Always

apiContainer:
  name: cve-rag-api
  image: dongrep/cve-rag-api
  tag: latest
  imagePullPolicy: Always

uiContainer:
  name: chatbot-ui
  image: dongrep/cve-rag-ui
  tag: latest
  imagePullPolicy: Always
  api_url: http://chatbot-api-service.chatbot-ns.svc.cluster.local:8080/recommend

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: x== 

db_secrets:
  openai_api_key: c2stcHJvai05X05rVnJjWV9KOC1ZMmh6RmZrM1E5b0pmYVFmcGdiZy1xLUkzbHdUUmd1alR4NVhjY0c1ZnZNMkpDVDNCbGJrRkpaMG5rbkhRU21tMW83NDFuUjhuVFhoSFI5MGlxZHNaNGFtSVUyWG9oV1pzTUgwalNyWlh5dERWbGtBCg==
  flyway:
    password: ZG9uZ3JlcAo=
  type: Opaque

configMap:
  host: webapp-postgresql.psql-ns.svc.cluster.local
  db_port: 5432
  db: cve
  flyway:
    url: jdbc:postgresql://webapp-postgresql.psql-ns.svc.cluster.local:5432/cve
    user: piyush
    schema: cve

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "200m"
    memory: "400Mi"

autoscaling:
  minReplicas: "2"
  maxReplicas: "4"
  targetCPUUtilizationPercentage: "80"

pdb:
  minAvailable: "2"

rbac:
  automountServiceAccountToken: false
