apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiContainer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.apiContainer.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiContainer.name }} 
    spec:
      serviceAccountName: {{ .Values.name }}-sa
      automountServiceAccountToken: {{ .Values.rbac.automountServiceAccountToken }}
      restartPolicy: {{ .Values.restartPolicy }}
      
      containers:
      - name: {{ .Values.apiContainer.name }}
        image: {{ .Values.apiContainer.image }}:{{ .Values.apiContainer.tag }}
        imagePullPolicy: {{ .Values.apiContainer.imagePullPolicy }}
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        ports:
          - containerPort: 8080

        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: host
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: db
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: db_port
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: flyway_user
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.name}}-db-secrets
                key: openai_api_key
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Values.name}}-db-secrets
                key: flyway_password
          - name: GIN_MODE
            value: debug

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }} 
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.name }} 
              topologyKey: topology.kubernetes.io/zone

      imagePullSecrets:
      - name: {{ .Values.name }}-pull-secrets
