apiVersion: v1
kind: Service
metadata:
  name: chatbot-api-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.apiContainer.name }} 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
