apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.uiContainer.name }} 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
