apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.uiContainer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.uiContainer.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.uiContainer.name }} 
    spec:
      serviceAccountName: {{ .Values.name }}-sa
      automountServiceAccountToken: {{ .Values.rbac.automountServiceAccountToken }}
      restartPolicy: {{ .Values.restartPolicy }}
      
      containers:
      - name: {{ .Values.uiContainer.name }}
        image: {{ .Values.uiContainer.image }}:{{ .Values.uiContainer.tag }}
        imagePullPolicy: {{ .Values.uiContainer.imagePullPolicy }}
        ports:
          - containerPort: 8501

        env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: api_url

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }} 
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}



      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.name }} 
              topologyKey: topology.kubernetes.io/zone

      imagePullSecrets:
      - name: {{ .Values.name }}-pull-secrets
