apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: chatbot-virtualservice
  namespace: chatbot-ns 
spec:
  hosts:
    - "chatbot.dev.clustering.ninja"
  gateways:
    - chatbot-gateway
  http:
    - match:
      route:
        - destination:
            host: chatbot-ui-service.chatbot-ns.svc.cluster.local
            port:
              number: 8501
        
